#################################################################################################################
####################################### SSL REVERSE PROXY TESTING ###############################################
#################################################################################################################
# This docker-compose provides ssl reverse proxy setup allowing to test the moodle's behavior over ssl reverse proxy
# For reverse proxy we are using the nginx webserver
#################################################################################################################
version: '2'
services:
# Reverse Proxy testing
  nginx_reverse:
    image: nginx:alpine
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8084:8084"
      - "8085:8085"
      - "8086:8086"
      - "6440:6440"
      - "6441:6441"
      - "6442:6442"
      - "6444:6444"
      - "6445:6445"
      - "6446:6446"
    links:
      - 'moodle_mysql_reverse'
      - 'moodle_maria_reverse'
      - 'moodle_psql_reverse'
      - 'nginx_mysql_reverse'
      - 'nginx_maria_reverse'
      - 'nginx_pgsql_reverse'
    restart: always
    volumes:
      - './conf/nginx/nginx_ssl_reverse.conf:/etc/nginx/nginx.conf:ro'
      - './conf/certs:/etc/nginx/certs:ro'

##################### Images for test ##########################################


############# Apache based variants ############################################

  moodle_mysql_db_reverse:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ONETIME_PASSWORD: "yes"
      MYSQL_DATABASE: "${MOODLE_DB_NAME}"
      MYSQL_USER: '${MOODLE_MYSQL_USER}'
      MYSQL_PASSWORD: '${MOODLE_MYSQL_PASSWORD}'

  moodle_mysql_reverse:
    image: ellakcy/moodle:mysql_maria_apache
    links:
      - "moodle_mysql_db_reverse:moodle_db"
    environment:
      MOODLE_DB_HOST: "moodle_db"
      MOODLE_DB_NAME: "${MOODLE_DB_NAME}"
      MOODLE_DB_USER: '${MOODLE_MYSQL_USER}'
      MOODLE_DB_PASSWORD: "${MOODLE_MYSQL_PASSWORD}"
      MOODLE_ADMIN: "${MOODLE_ADMIN}"
      MOODLE_ADMIN_PASSWORD: "${MOODLE_ADMIN_PASSWORD}"
      MOODLE_URL: "https://0.0.0.0:6440"
      MOODLE_REVERSE_LB: "true"
      MOODLE_SSL: "true"

  # postgresql running variant
  moodle_psql_db_reverse:
    image: postgres
    environment:
      POSTGRES_DB: "${MOODLE_DB_NAME}"
      POSTGRES_USER: '${MOODLE_MYSQL_USER}'
      POSTGRES_PASSWORD: '${MOODLE_MYSQL_PASSWORD}'

  moodle_psql_reverse:
    build:
      context: .
      dockerfile: dockerfiles/apache/Dockerfile_postgrtesql
    image: ellakcy/moodle:postgresql_apache
    links:
      - "moodle_psql_db_reverse:moodle_db"
    environment:
      MOODLE_DB_HOST: "moodle_db"
      MOODLE_DB_NAME: "${MOODLE_DB_NAME}"
      MOODLE_DB_USER: '${MOODLE_MYSQL_USER}'
      MOODLE_DB_PASSWORD: "${MOODLE_MYSQL_PASSWORD}"
      MOODLE_ADMIN: "${MOODLE_ADMIN}"
      MOODLE_ADMIN_PASSWORD: "${MOODLE_ADMIN_PASSWORD}"
      MOODLE_URL: "https://0.0.0.0:6441"
      MOODLE_REVERSE_LB: "false"
      MOODLE_SSL: "true"

  # Testing mariadb support
  moodle_maria_db_reverse:
      image: mariadb:10.2
      environment:
        MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        MYSQL_ONETIME_PASSWORD: "yes"
        MYSQL_DATABASE: "${MOODLE_DB_NAME}"
        MYSQL_USER: '${MOODLE_MYSQL_USER}'
        MYSQL_PASSWORD: '${MOODLE_MYSQL_PASSWORD}'

  moodle_maria_reverse:
      image: ellakcy/moodle:mysql_maria_apache
      links:
        - "moodle_mysql_reverse"
        - "moodle_maria_db_reverse:moodle_db"
      environment:
        MOODLE_DB_HOST: "moodle_db"
        MOODLE_DB_NAME: "${MOODLE_DB_NAME}"
        MOODLE_DB_USER: '${MOODLE_MYSQL_USER}'
        MOODLE_DB_PASSWORD: "${MOODLE_MYSQL_PASSWORD}"
        MOODLE_ADMIN: "${MOODLE_ADMIN}"
        MOODLE_ADMIN_PASSWORD: "${MOODLE_ADMIN_PASSWORD}"
        MOODLE_URL: "https://0.0.0.0:6442"
        MOODLE_REVERSE_LB: "true"
        MOODLE_SSL: "true"

########################### Alpine fpm based images ############################

  #Mysql variant
  nginx_mysql_reverse:
   image: nginx:alpine
   ports:
     - "6070:6070"
   volumes:
     - './conf/nginx/nginx_mysql_reverse.conf:/etc/nginx/nginx.conf:ro'
   links:
     - 'moodle_alpine_fpm_mysql_reverse'
   volumes_from:
     - 'moodle_alpine_fpm_mysql_reverse'

  moodle_mysql_alpine_db_reverse:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ONETIME_PASSWORD: "yes"
      MYSQL_DATABASE: "${MOODLE_DB_NAME}"
      MYSQL_USER: '${MOODLE_MYSQL_USER}'
      MYSQL_PASSWORD: '${MOODLE_MYSQL_PASSWORD}'

  moodle_alpine_fpm_mysql_reverse:
    build:
      context: .
      dockerfile: dockerfiles/fpm_alpine/Dockerfile_mysql
    image: ellakcy/moodle:mysql_maria_fpm_alpine
    links:
      - "moodle_mysql_alpine_db_reverse:moodle_db"
    environment:
      MOODLE_DB_HOST: "moodle_db"
      MOODLE_DB_NAME: "${MOODLE_DB_NAME}"
      MOODLE_DB_USER: '${MOODLE_MYSQL_USER}'
      MOODLE_DB_PASSWORD: "${MOODLE_MYSQL_PASSWORD}"
      MOODLE_ADMIN: "${MOODLE_ADMIN}"
      MOODLE_ADMIN_PASSWORD: "${MOODLE_ADMIN_PASSWORD}"
      MOODLE_URL: "https://0.0.0.0:6445"
      MOODLE_REVERSE_LB: "true"
      MOODLE_SSL: "true"

  #Mariadb for dempnstration
  nginx_maria_reverse:
   image: nginx:alpine
   ports:
     - "6071:6071"
   volumes:
     - './conf/nginx/nginx_mariadb_reverse.conf:/etc/nginx/nginx.conf:ro'
   links:
     - 'moodle_alpine_fpm_mariadb_reverse'
   volumes_from:
     - 'moodle_alpine_fpm_mariadb_reverse'

  moodle_mariadb_alpine_db_reverse:
    image: mariadb:10.2
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ONETIME_PASSWORD: "yes"
      MYSQL_DATABASE: "${MOODLE_DB_NAME}"
      MYSQL_USER: '${MOODLE_MYSQL_USER}'
      MYSQL_PASSWORD: '${MOODLE_MYSQL_PASSWORD}'

  moodle_alpine_fpm_mariadb_reverse:
    image: ellakcy/moodle:mysql_maria_fpm_alpine
    links:
      - "moodle_mariadb_alpine_db_reverse:moodle_db"
    environment:
      MOODLE_DB_HOST: "moodle_db"
      MOODLE_DB_NAME: "${MOODLE_DB_NAME}"
      MOODLE_DB_USER: '${MOODLE_MYSQL_USER}'
      MOODLE_DB_PASSWORD: "${MOODLE_MYSQL_PASSWORD}"
      MOODLE_ADMIN: "${MOODLE_ADMIN}"
      MOODLE_ADMIN_PASSWORD: "${MOODLE_ADMIN_PASSWORD}"
      MOODLE_URL: "https://0.0.0.0:6444"
      MOODLE_REVERSE_LB: "true"
      MOODLE_SSL: "true"

  #Postgresql
  nginx_pgsql_reverse:
      image: nginx:alpine
      ports:
        - "6072:6072"
      volumes:
        - './conf/nginx/nginx_psql_reverse.conf:/etc/nginx/nginx.conf:ro'
      links:
        - 'moodle_alpine_fpm_psql_reverse'
      volumes_from:
        - 'moodle_alpine_fpm_psql_reverse'

  moodle_psql_alpine_db_reverse:
      image: postgres
      environment:
        POSTGRES_DB: "${MOODLE_DB_NAME}"
        POSTGRES_USER: '${MOODLE_MYSQL_USER}'
        POSTGRES_PASSWORD: '${MOODLE_MYSQL_PASSWORD}'

  moodle_alpine_fpm_psql_reverse:
      build:
        context: .
        dockerfile: dockerfiles/fpm_alpine/Dockerfile_postgresql
      image: ellakcy/moodle:postgresql_fpm_alpine
      links:
        - "moodle_psql_alpine_db_reverse:moodle_db"
      environment:
        MOODLE_DB_HOST: "moodle_db"
        MOODLE_DB_NAME: "${MOODLE_DB_NAME}"
        MOODLE_DB_USER: '${MOODLE_MYSQL_USER}'
        MOODLE_DB_PASSWORD: "${MOODLE_MYSQL_PASSWORD}"
        MOODLE_ADMIN: "${MOODLE_ADMIN}"
        MOODLE_ADMIN_PASSWORD: "${MOODLE_ADMIN_PASSWORD}"
        MOODLE_URL: "https://0.0.0.0:6446"
        MOODLE_REVERSE_LB: "true"
        MOODLE_SSL: "true"
