FROM  ellakcy/moodle:alpine_fpm_base
MAINTAINER Dimitrios Desyllas <pcmagas@disroot.org>

COPY ./scripts/entrypoint.sh /usr/local/bin/entrypoint.sh
COPY ./scripts/detect_mariadb.php /opt/detect_mariadb.php

RUN chmod +x /usr/local/bin/entrypoint.sh && \
    apk add --update postgresql-dev &&\
    docker-php-ext-install pdo pgsql pdo_pgsql &&\
    rm -rf /var/cache/apk/*

# Later we may need a different entrypoint
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["php-fpm"]
