# Dockerfile for moodle instance.

FROM  php:7.0-fpm-alpine
MAINTAINER Dimitrios Desyllas <pcmagas@disroot.org>
#Original Maintainer Jon Auer <jda@coldshore.com>

# Replace for later version
ARG VERSION=33

VOLUME ["/var/moodledata"]
EXPOSE 80

# Let the container know that there is no tty
ENV \
		MOODLE_URL http://0.0.0.0 \
    MOODLE_ADMIN admin \
    MOODLE_ADMIN_PASSWORD Admin~1234 \
    MOODLE_ADMIN_EMAIL admin@example.com \
    MOODLE_DB_TYPE 'mysqli' \
    MOODLE_DB_HOST '' \
    MOODLE_DB_PASSWORD '' \
    MOODLE_DB_USER '' \
    MOODLE_DB_NAME '' \
    MOODLE_DB_PORT '3306'

# Installing php and external tools
RUN \
		apk add --update curl rsync unzip netcat-openbsd libxml2-dev icu-dev libmcrypt-dev libpng-dev  &&\
 		docker-php-ext-install xmlrpc && \
		docker-php-ext-install mbstring && \
		docker-php-ext-install zip && \
		docker-php-ext-install intl && \
 		docker-php-ext-install soap && \
 		docker-php-ext-install mcrypt && \
		docker-php-ext-install gd && \
		echo "Installing moodle" && \
		curl https://download.moodle.org/download.php/direct/stable${VERSION}/moodle-latest-${VERSION}.zip -o /tmp/moodle-latest.zip  && \
		rm -rf /var/www/html/index.html && \
		cd /tmp &&	unzip /tmp/moodle-latest.zip && cd / \
		mkdir -p /usr/src/moodle && \
		mv /tmp/moodle /usr/src/ && \
		chown www-data:www-data -R /usr/src/moodle && \
		apk del -y unzip curl &&\
    rm -rf /var/cache/apk/*

COPY ./scripts/moodle-config.php /usr/src/moodle/config.php
