# Dockerfile for moodle instance.
# Forked from Jonathan Hardison's <jmh@jonathanhardison.com> docker version. https://github.com/jmhardison/docker-moodle

FROM  ellakcy/moodle:apache_base
MAINTAINER Dimitrios Desyllas <pcmagas@disroot.org>
#Original Maintainer Jon Auer <jda@coldshore.com>

ENV DEBIAN_FRONTEND noninteractive

VOLUME ["/var/moodledata"]
EXPOSE 80

COPY ./scripts/entrypoint.sh /usr/local/bin/entrypoint.sh
COPY ./scripts/detect_mariadb.php /opt/detect_mariadb.php

# Installing php and external tools
#RUN chmod +x /usr/local/bin/entrypoint.sh && \
#    apt-get update && \
#    apt-get install mysql-client &&\
#    docker-php-ext-install pdo mysqli pdo_mysql &&\
#		apt-get autoremove -y &&\
#		apt-get autoclean &&\
#		rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* cache/* /var/lib/log/*

RUN chmod +x /usr/local/bin/entrypoint.sh && \
    apt-get update && \
    apt-get install -y libmysqlclient-dev netcat &&\
    docker-php-ext-install pdo mysqli pdo_mysql &&\
    apt-get autoremove -y &&\
    apt-get autoclean &&\
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* cache/* /var/lib/log/*

# Later we may need a different entrypoint
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
