# Dockerfile for moodle instance.
# Forked from Jonathan Hardison's <jmh@jonathanhardison.com> docker version. https://github.com/jmhardison/docker-moodle

FROM  ellakcy/moodle:apache_base
MAINTAINER Dimitrios Desyllas <pcmagas@disroot.org>
#Original Maintainer Jon Auer <jda@coldshore.com>

VOLUME ["/var/moodledata"]
EXPOSE 80

COPY ./scripts/entrypoint.sh /usr/local/bin/entrypoint.sh

# Installing php and external tools
RUN chmod +x /usr/local/bin/entrypoint.sh && \
    apt-get update && \
    apt-get install -y netcat libghc-postgresql-simple-dev &&\
    docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql && \
    docker-php-ext-install pdo pdo_pgsql &&\
		apt-get autoremove -y &&\
		apt-get autoclean &&\
		rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* cache/* /var/lib/log/*


# Later we may need a different entrypoint
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
